# Generated by Django 3.1.4 on 2021-02-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='login',
            name='emailid',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.TextField(max_length=50),
        ),
    ]
